epdms:
    openapi:
        dev-url: https://epdms-api.com
        local-url: http://localhost:8040
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
resilience4j:
    circuitbreaker:
        configs:
            default:
                automaticTransitionFromOpenToHalfOpenEnabled: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                registerHealthIndicator: true
                slidingWindowSize: 10
                waitDurationInOpenState: 5s
server:
    port: 8040
    shutdown: GRACEFUL
spring:
    application:
        name: EPDMS-REACTIVE-APP
    lifecycle:
        timeout-per-shutdown-phase: 1m
    main:
        allow-circular-references: true
    r2dbc:
        password: postgres
        url: r2dbc:postgresql://localhost:5432/postgres
        username: postgres
# Disabled Config Server for now
    cloud:
        config:
            enabled: false

# Uncomment these changes when you required config server configurations
    #config:
        #import: configserver:http://localhost:8030
springdoc:
    api-docs:
        path: /epdms-api-docs
    swagger-ui:
        filter: true
        path: /epdms-documentation
        tryItOutEnabled: true
